apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: {{ .Values.namespaces.database }}
spec:
  capacity:
    storage: {{ .Values.mongodb.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mongodb.path }}
